# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Paul Yasi
tagline:          'My Blog'
description:      'Blogging about web development, open source, real food, life, the universe, and everything.'
url:              http://paulyasi.com

author:
  name:           'Paul Yasi'
  url:            http://paulyasi.com

paginate:         5

